language: generic
sudo: required
services: 
  - docker

#before_install:
  - docker build -t joshmuepu/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true joshmuepu/docker-react npm run test